name: Integration tests

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  integration_tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v7
    - name: Setup Go
      uses: actions/setup-go@v7
      with:
        go-version: stable
    - name: Run integration tests
      env:
        OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
      run: go test -v -tags=integration ./api_integration_test.go
